version: 2

defaults: &defaults
    working_directory: ~/js-textile-go-daemon
    docker:
        - image: node:10.13.0

jobs:
    lint-test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - restore_cache:
                key: node-v1-{{ checksum "package.json" }}-{{ arch }}
            - run: npm install --unsafe-perm
            - run:
                name: lint
                command: |
                    npm run lint
            - save_cache:
                key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
                paths:
                    - ~/.cache/npm
            - save_cache:
                key: node-v1-{{ checksum "package.json" }}-{{ arch }}
                paths:
                    - node_modules
    deploy:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - restore_cache:
                key: node-v1-{{ checksum "package.json" }}-{{ arch }}
            - run: npm install
            - attach_workspace:
                at: ~/js-textile-go-daemon
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/js-textile-go-daemon/.npmrc
            - run:
                name: Publish package
                command: npm publish --access=public --unsafe-perm

workflows:
    version: 2
    js-textile-go-daemon:
        jobs:
            - lint-test:
                filters:
                    tags:
                        only: /^v.*/
            - deploy:
                requires:
                    - lint-test
                filters:
                    tags:
                        only: /^v.*/
                    branches:
                        ignore: /.*/
